/* =========================================================================
 * ch04 "The Morality Test"
 * STUB generated by tools/new-chapter.js. Replace with the real chapter.
 * Read play/ENGINE_API.md and copy patterns from chapters/ch00/chapter.js.
 * Only edit files inside chapters/ch04/.
 *   Chapter-local flags: 'ch04_xxx'.  Cross-chapter flags: camelCase (see ENGINE_API.md).
 * Test: node test/smoke.js ch04
 * ========================================================================= */
(function () {
  'use strict';

  var room = {
    name: 'The Morality Test',
    tiles: [
      '###########',
      '#.........#',
      '#....@....#',
      '#.........#',
      '#####D#####'
    ],
    ambient: 'drone',
    npcs: [],
    objects: [
      { id: 'placeholder', at: [7, 1], prop: 'note', solid: false }
    ],
    zones: [],
    exits: []
  };

  G.registerChapter({
    id: 'ch04',
    title: 'The Morality Test',
    maps: { room: room },
    cast: {},
    testDefaults: {},

    start: async function (api) {
      await api.goRoom('room');
      await api.narrate('[ch04: The Morality Test] This chapter has not been written yet.');
      api.objective('Read the note');
      await api.waitForInteract('placeholder');
      await api.think('To be continued.');
      api.set('ch04_stubDone', true);
      api.completeChapter();
    }
  });
})();
