#!/usr/bin/env node
/* =========================================================================
 * Scaffold chapter(s) and add/update their manifest entries.
 *
 *   node tools/new-chapter.js ch05 "Title"                     one chapter
 *   node tools/new-chapter.js ch01 "One" ch02 "Two" ch03 "Three"   many at once
 *   node tools/new-chapter.js --json chapters.json             [{id,title,number?,hidden?,files?}, ...]
 * Options (apply to every chapter in the call):
 *   --number N      chapter number shown on the title card (default: digits of the id)
 *   --hidden        exclude from New Game ordering (like ch00)
 *   --files a.js,b.js   script files in load order (default chapter.js); first must exist or is created
 *   --force         overwrite an existing chapter.js with the stub template
 *   --dry           print what would happen
 *
 * Idempotent: re-running updates the manifest entry (title/number/files) and
 * never overwrites an existing chapter.js unless --force.
 * Manifest entries are kept sorted by number (ties: id).
 * ========================================================================= */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const MANIFEST = path.join(ROOT, 'chapters', 'manifest.js');

const argv = process.argv.slice(2);
const opts = { hidden: false, force: false, dry: false, number: null, files: null, json: null };
const pos = [];
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--hidden') opts.hidden = true;
  else if (a === '--force') opts.force = true;
  else if (a === '--dry') opts.dry = true;
  else if (a === '--number') opts.number = argv[++i];
  else if (a === '--files') opts.files = argv[++i].split(',').map((s) => s.trim()).filter(Boolean);
  else if (a === '--json') opts.json = argv[++i];
  else if (a === '-h' || a === '--help') { usage(); process.exit(0); }
  else pos.push(a);
}
function usage() {
  console.log('usage: node tools/new-chapter.js <id> "<title>" [<id> "<title>" ...] [--number N] [--hidden] [--files a.js,b.js] [--force]\n       node tools/new-chapter.js --json list.json');
}

let specs = [];
if (opts.json) specs = JSON.parse(fs.readFileSync(opts.json, 'utf8'));
else {
  if (pos.length < 1) { usage(); process.exit(1); }
  for (let i = 0; i < pos.length; i += 2) specs.push({ id: pos[i], title: pos[i + 1] });
}

function readManifest() {
  const ctx = { G: {} };
  vm.runInNewContext(fs.readFileSync(MANIFEST, 'utf8'), ctx);
  return ctx.G.manifest;
}
function writeManifest(m) {
  const header = `/* =========================================================================
 * chapters/manifest.js: the ordered chapter list + game info.
 * Edit with: node tools/new-chapter.js <id> "<title>" [--number N] [--hidden] [--files a.js,b.js]
 * (chapter agents never edit this file; the orchestrator does.)
 * Each chapter: { id, number, title, files: [paths inside chapters/<id>/], hidden? }
 * New Game plays non-hidden chapters in array order.
 * ========================================================================= */
`;
  const chapters = m.chapters.map((c) => '    ' + JSON.stringify(c).replace(/^\{/, '{ ').replace(/\}$/, ' }').replace(/,"/g, ', "').replace(/":/g, '": ')).join(',\n');
  const game = JSON.stringify(m.game || {}, null, 2).replace(/\n/g, '\n  ');
  const out = `${header}G.manifest = {\n  "game": ${game},\n  "chapters": [\n${chapters}\n  ]\n};\n`;
  fs.writeFileSync(MANIFEST, out);
}

function template(id, title, number) {
  const local = id + '_';
  return `/* =========================================================================
 * ${id} "${title}"
 * STUB generated by tools/new-chapter.js. Replace with the real chapter.
 * Read play/ENGINE_API.md and copy patterns from chapters/ch00/chapter.js.
 * Only edit files inside chapters/${id}/.
 *   Chapter-local flags: '${local}xxx'.  Cross-chapter flags: camelCase (see ENGINE_API.md).
 * Test: node test/smoke.js ${id}
 * ========================================================================= */
(function () {
  'use strict';

  var room = {
    name: '${title.replace(/'/g, "\\'")}',
    tiles: [
      '###########',
      '#.........#',
      '#....@....#',
      '#.........#',
      '#####D#####'
    ],
    ambient: 'drone',
    npcs: [],
    objects: [
      { id: 'placeholder', at: [7, 1], prop: 'note', solid: false }
    ],
    zones: [],
    exits: []
  };

  G.registerChapter({
    id: '${id}',
    title: '${title.replace(/'/g, "\\'")}',
    maps: { room: room },
    cast: {},
    testDefaults: {},

    start: async function (api) {
      await api.goRoom('room');
      await api.narrate('[${id}: ${title.replace(/'/g, "\\'")}] This chapter has not been written yet.');
      api.objective('Read the note');
      await api.waitForInteract('placeholder');
      await api.think('To be continued.');
      api.set('${local}stubDone', true);
      api.completeChapter();
    }
  });
})();
`;
}

const m = readManifest();
m.chapters = m.chapters || [];
for (const s of specs) {
  if (!s.id || !/^[a-z][a-z0-9_]*$/i.test(s.id)) { console.error(`bad chapter id "${s.id}" (use ch05 style)`); process.exit(1); }
  const title = s.title || (m.chapters.find((c) => c.id === s.id) || {}).title || s.id;
  const digits = (s.id.match(/\d+/) || ['0'])[0];
  const number = s.number != null ? +s.number : opts.number != null ? +opts.number : +digits;
  const files = s.files || opts.files || ['chapter.js'];
  const hidden = s.hidden != null ? !!s.hidden : opts.hidden;
  const entry = { id: s.id, number, title, files };
  if (hidden) entry.hidden = true;
  const idx = m.chapters.findIndex((c) => c.id === s.id);
  if (idx >= 0) {
    const old = m.chapters[idx];
    if (!s.files && !opts.files && old.files) entry.files = old.files;
    if (!s.title) entry.title = old.title;
    if (old.hidden && s.hidden == null && !opts.hidden) entry.hidden = true;
    m.chapters[idx] = entry;
    console.log(`updated manifest entry ${s.id}`);
  } else { m.chapters.push(entry); console.log(`added manifest entry ${s.id}`); }

  const dir = path.join(ROOT, 'chapters', s.id);
  const main = path.join(dir, entry.files[0]);
  if (!fs.existsSync(main) || opts.force) {
    if (!opts.dry) { fs.mkdirSync(dir, { recursive: true }); fs.writeFileSync(main, template(s.id, entry.title, number)); }
    console.log(`${opts.force && fs.existsSync(main) ? 'overwrote' : 'created'} chapters/${s.id}/${entry.files[0]}`);
  } else console.log(`kept existing chapters/${s.id}/${entry.files[0]}`);
  for (const f of entry.files.slice(1)) {
    const fp = path.join(dir, f);
    if (!fs.existsSync(fp) && !opts.dry) { fs.writeFileSync(fp, `/* ${s.id}/${f}: extra chapter file (loaded before/after chapter.js in manifest order). Use G.chapterBag('${s.id}') to share data. */\n`); console.log(`created chapters/${s.id}/${f}`); }
  }
}
m.chapters.sort((a, b) => (a.number - b.number) || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
if (!opts.dry) writeManifest(m);
console.log(`manifest now has ${m.chapters.length} chapter(s): ${m.chapters.map((c) => c.id).join(', ')}`);
