/* =========================================================================
 * ch11 "The Maze"
 * STUB generated by tools/new-chapter.js. Replace with the real chapter.
 * Read play/ENGINE_API.md and copy patterns from chapters/ch00/chapter.js.
 * Only edit files inside chapters/ch11/.
 *   Chapter-local flags: 'ch11_xxx'.  Cross-chapter flags: camelCase (see ENGINE_API.md).
 * Test: node test/smoke.js ch11
 * ========================================================================= */
(function () {
  'use strict';

  var room = {
    name: 'The Maze',
    tiles: [
      '###########',
      '#.........#',
      '#....@....#',
      '#.........#',
      '#####D#####'
    ],
    ambient: 'drone',
    npcs: [],
    objects: [
      { id: 'placeholder', at: [7, 1], prop: 'note', solid: false }
    ],
    zones: [],
    exits: []
  };

  G.registerChapter({
    id: 'ch11',
    title: 'The Maze',
    maps: { room: room },
    cast: {},
    testDefaults: {},

    start: async function (api) {
      await api.goRoom('room');
      await api.narrate('[ch11: The Maze] This chapter has not been written yet.');
      api.objective('Read the note');
      await api.waitForInteract('placeholder');
      await api.think('To be continued.');
      api.set('ch11_stubDone', true);
      api.completeChapter();
    }
  });
})();
